query Email($email: String!) {
  person(email: "bob@jonesfamily.com") {
    id
    identifiers {
      SSNs {
        value
      }
      emails {
        value
      }
      phoneNumbers {
        use
        value
      }
    }
    names {
      use
      fullName
    }
    postalAddresses {
      use
      addressFull
    }
    birthDate
    gender
  }
}
query Email($email: String!) {
  person(email: $email) {
    id
    identifiers {
      SSNs {
        value
      }
      emails {
        value
      }
      phoneNumbers {
        use
        value
      }
    }
    names {
      use
      fullName
    }
    postalAddresses {
      use
      addressFull
    }
    birthDate
    gender
  }
}

